# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fd132b0c5efe6e724ec44a1aa2e99033d28f4649f688e55f328056bd3dcc4b659557df51239d603e62d14eeb89271229cc248b1ed7a59e623152afbdac5e95

test:
  secret_key_base: 3bf1752d1379102e68f940e62b724e759d7a89a63fc67fb4563d6f0dc4d6aff4aaf7b85d01befd174b838179ec2af81c6895c5c2b6e0d457d48d50a9c450eb96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
